spring:
  datasource:
    url: jdbc:mysql://192.168.1.17:3306/rk_dev
    username: rk_dev_user
    password: gkdev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistance:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: gkdev_database_create.sql